### ISSUE TITLE
part4 test cases

### ISSUE THREAD

**Issue by 142ayushkumar** [beaunus/stanford-algs#32]
my code gives correct answer for all the test cases in ur repository but for all the questions in programming assignment it gives NULL which is not the correct answer,add some careful test cases please,i m unable to find out my mistake

btw thanks for making this amazing repository

**Comment by beaunus** [comment]
Kumar,

Thank you for your interest in helping with this project.

I'm not sure I completely understand your question.

What do you mean "for all the questions in programming assignment it gives NULL"?

I look forward to hearing from you.

**Comment by 142ayushkumar** [comment]
i mean it detects negative cycles in each question in the problem given,but it passes all your test cases

**Comment by beaunus** [comment]
Which assignment in part 4 are you talking about?

**Comment by 142ayushkumar** [comment]
assignment 1 ,i implemented using bellman ford

**Comment by beaunus** [comment]
I see.  I'll look into this and let you know soon.

**Comment by beaunus** [comment]
Kumar,

I realized something that may help you.

For our test cases, all of the shortest paths have vertices in _ascending order_.  However, for the assignment itself, the shortest path has vertices that are not in any particular order.

For example:
In our repository, all the test cases for this assignment have shortest paths that look something like this:

```
[1, 5, 7, 8, 543, 765]  (all in ascending order)
```

But for the assignment itself, some of the shortest paths look something like this:

```
[54, 65, 2, 654, 43, 543, 199] (not in ascending order)
```

I don't know if this will help you to fix your _negative cycle_ detection problem, but I hope that it helps.
