### ISSUE TITLE
2.2 Test Case Error

### ISSUE THREAD

**Issue by beaunus** [beaunus/stanford-algs#33]
Ravishankar Joshi suggested that the results did not account for symmetric edges.  It appears that our solution was based on a _directed graph_, rather than an _undirected graph_.

**Comment by beaunus** [comment]
Please confirm that the new test cases are correct and I will merge them to master.

https://github.com/beaunus/stanford-algs/tree/2.2-useUndirectedGraph/testCases/course2/assignment2Dijkstra

**Comment by ravibitsgoa** [comment]
I checked out with my solution for undirected graphs, and my answer is matching output files. Now, the test-cases are correct.

**Comment by beaunus** [comment]
Thank you.  I have merged the new test cases to master.

**Comment by Stevan0102** [comment]
Hi, it seems that your test cases are still in directed graph. E.g. https://github.com/beaunus/stanford-algs/blob/master/testCases/course2/assignment2Dijkstra/input_random_4_4.txt

**Comment by beaunus** [comment]
Thank you, Stevan. I see.

I think that the solutions are correct if the client program interprets the input as an undirected graph. However, like Stevan0102 said, the test case files do not show edges going in both directions. 

This week is a bit busy for me, including the weekend. I'll try my best to correct this as soon as possible. I can however, test any recommended alternatives rather quickly. I will keep you all informed as this progresses.

**Comment by beaunus** [comment]
Thank you for being patient.

I think that I have fixed the problem. Now, all input files have the edges in the adjacency list for _both_ vertices.

Please let me know when you have confirmed the correctness of the test cases.

https://github.com/beaunus/stanford-algs/tree/2.2-directed_graph/testCases/course2/assignment2Dijkstra

Thank you.
Beau
