### ISSUE TITLE
Test cases for 1.1 incorrectly named causing tester.py to fail

### ISSUE THREAD

**Issue by d5kippy** [beaunus/stanford-algs#34]
2 test cases contributed by Rahmeen are incorrectly named, and cause tester.py to fail.

These 4 files:
input_Rahmeen14_01.txt
input_Rahmeen14_02.txt
output_Rahmeen14_01.txt
output_Rahmeen14_02.txt

need to be renamed to:
input_Rahmeen_14_1.txt
input_Rahmeen_14_2.txt
output_Rahmeen_14_1.txt
output_Rahmeen_14_2.txt

**Comment by dgrcode** [comment]
Hi @d5kippy good catch. In fact, the code for python.py is not ready to handle names that don't comply with the expected format. I'll fix the names of the files

**Comment by dgrcode** [comment]
Commit bb5de9c should fix it. Let me know if it doesn't to reopen the issue.
