### ISSUE TITLE
course3/assignment1SchedulingAndMST/question3 input is wrong

### ISSUE THREAD

**Issue by ijesonchen** [beaunus/stanford-algs#37]
expected input is:
[number_of_nodes] [number_of_edges]
and then number_of_edges lines below.

But the line count of edges and [number_of_edges] is not equal.
For example, the first line of [input_random_11_40.txt](https://github.com/ijesonchen/stanford-algs/blob/master/testCases/course3/assignment1SchedulingAndMST/question3/input_random_11_40.txt) is
 > 40 78

but only 51 edges below.

Will you consider to fix it?
Thank you.

**Comment by beaunus** [comment]
Jeson,

Thank you for bring this up. I’ll look into it soon.

Cheers,
Beau

**Comment by beaunus** [comment]
Jeson,

I have updated the files with the correct number of edges. Thank you for pointing this out.

If you notice any other problems, please let me know.

Beau
