### ISSUE TITLE
Distance for Node 99 should be 333, not 331

### ISSUE THREAD

**Issue by adam-hurwitz** [beaunus/stanford-algs#38]
Distance for Node 99 should be **333**, not **331**

https://github.com/beaunus/stanford-algs/blob/master/testCases/course2/assignment2Dijkstra/output_random_1_4.txt

**Comment by beaunus** [comment]
Adam,

Thank you for contributing to this repository.

I'd like to see your rationale behind this. According to my computation, here is the shortest path from 1->99:

99, 96, 122, 14, 44, 16, 132, 120, 147, 100, 169, 84, 103, 8, 1

![img_5216](https://user-images.githubusercontent.com/535311/34704208-f4f39586-f53a-11e7-8232-de37fc23eafb.JPG)

What do you think?

Beau

**Comment by adam-hurwitz** [comment]
I found some bugs in my code. I just re-ran and see 331 distance for Node 99 as well. Thanks for looking into this :-)
