### ISSUE TITLE
can you publish this package? would be great to install it and have access to test cases that way

### ISSUE THREAD

**Issue by dey-dey** [beaunus/stanford-algs#39]

**Comment by beaunus** [comment]
Amadeus,

I am interested in your question, but I don't completely understand. What do you mean by "publish". Maybe this is a GitHub feature that I have not used before.

Beau

**Comment by dey-dey** [comment]
publish it to a repository (npm, maven, python), for example:

- python: https://packaging.python.org/tutorials/distributing-packages/
- java: https://maven.apache.org/guides/mini/guide-central-repository-upload.html

that way we can include the files in our own repositories

**Comment by beaunus** [comment]
I see what you mean now about publishing.

In my view, this repository is mostly focused on the input text files. I'm willing to explore publishing the code in maven or pip, but I don't yet see the use case. As far as I know, the way to use this repository is:

1. Clone the code onto your local machine.
1. Follow the instructions in the "tester" folder.

My sense is that the purpose of publishing a library is so others can use your code *within* their application. Can you please give me an example of how you would use the code if it were published on maven or pip?

Thank you. :)

**Comment by dey-dey** [comment]
i should state that my goal is to show my tests are all passing in an automated way.

so when building a library it's often nice to have a badge which shows your tests are reliably passing. so to be able to do this it'd be nice to be able to import tests and run them in my own repo (without copy pasting, so i can always pull in the latest tests). 

but it sounds like that is not gonna be possible
