### ISSUE TITLE
test cases could be better formatted for those that want to incorporate them into unit tests

### ISSUE THREAD

**Issue by dey-dey** [beaunus/stanford-algs#40]
rather than having seperate files, you could just add a new line for the desired output. that way you'd just scan txt files and one by one

**Comment by beaunus** [comment]
Amadeus,

Thank you for your idea about this.

I'll try to explain my rationale about the test case format. I think that your idea is good. But, in my opinion, I think that it's better to keep the input files exactly like the assignment input files from the Coursera course.

I also understand the importance of automated testing. We have prepared a few "testers" that make it easy to test your code against all of our results. There are testers for Python and Java. There is also a generic tester that uses a language-agnostic shell script:

https://github.com/beaunus/stanford-algs/tree/master/tester/shell

What do you think?

Beau
