### ISSUE TITLE
Wrong testcase assertion

### ISSUE THREAD

**Issue by andreyvolosyuk** [beaunus/stanford-algs#43]
https://github.com/beaunus/stanford-algs/blob/master/testCases/course1/assignment2Inversions/input_beaunus_2_4.txt

There are 3 inversions: 3-1, 3-2 and 4-2

**Comment by beaunus** [comment]
Thank you for your interest in this project.

I just looked at https://github.com/beaunus/stanford-algs/blob/master/testCases/course1/assignment2Inversions/output_beaunus_2_4.txt.

The expected output is 3. I don’t understand the issue. What do you mean?

**Comment by andreyvolosyuk** [comment]
Isn't correct answer reflected in the title? I might comprehend in wrong way.
If file has name output_beaunus_2_4.txt, does it mean that input has 4 integers and aswer is 2?

**Comment by beaunus** [comment]
I see. It’s not completely obvious, so I see how you could misunderstand.

There is a section in the wiki that explains about the test case names.

https://github.com/beaunus/stanford-algs/wiki/Using-Test-Cases

Have a look there and please let us know if you have any further questions. Good luck with the course. :)
