### ISSUE TITLE
Test cases course 3 assignment2Clustering question 2 file name have two input sizes

### ISSUE THREAD

**Issue by Haolicopter** [beaunus/stanford-algs#47]
`input_random_10_16_18.txt`: this question test case name
`input_random_10_16.txt`: Other question test case name

This question test file names has two input sizes instead of one and python3 tester can only read one input size.

```
Traceback (most recent call last):
  File "tester/python3/tester.py", line 148, in <module>
    test(student_algorithm, test_cases_folder,  *option_values)
  File "tester/python3/tester.py", line 29, in test
    file_type, file_user, file_num, file_size = filename[:-4].split('_')
ValueError: too many values to unpack (expected 4)
```

**Comment by dgrcode** [comment]
Hi!

Thanks for raising this issue here. I saw you opened a PR https://github.com/beaunus/stanford-algs/pull/48. I'll have a look at it tomorrow.
