### ISSUE TITLE
Week2 assignment is about undirected graph

### ISSUE THREAD

**Issue by oren0e** [beaunus/stanford-algs#58]
The assignment for Dijkstra's algorithm is given on an undirected graph, but here all the test cases are for directed graphs. Is this on purpose? Can anyone explain why?

**Comment by styrmis** [comment]
Given the adjacency list format, to write out an undirected graph you write out edges in both directions.

So for example in [this test case](https://github.com/beaunus/stanford-algs/blob/master/testCases/course2/assignment2Dijkstra/input_random_10_16.txt) node 1 is connected to node 20 with weight 460, so if we look at the entry for node 20 we can see a reciprocal connection back to node 1 with the same weight (460).

**Comment by oren0e** [comment]
Thanks, I figured it out later. Closing the issue.
